### ISSUE TITLE
Augmented error message

### ISSUE THREAD

**Issue by kamekazemaster** [stevemao/get-pkg-repo#10]
Hi,

I was just about to implement [semantic-release-gitlab](https://gitlab.com/hyper-expanse/semantic-release-gitlab) when I always encountered the error message `No repository`.

When I [digged](https://gitlab.com/hyper-expanse/semantic-release-gitlab/issues/17) a bit deeper I found out that the error message came from an underlying module. This module ;)

The error message is getting thrown in [this](https://github.com/stevemao/get-pkg-repo/blob/1fd9902142452dc6eed86db7173dd7b78f7d78d5/index.js#L78) line. Would it be possible to change the error message to something more meaningful like `Missing repository field in package.json` or something like that?

**Comment by stevemao** [comment]
@kamekazemaster sure. PR welcome :)

**Comment by hbetts** [comment]
Filed #11

**Comment by hbetts** [comment]
Thank you @stevemao! I look forward to when it's publish to npm so I can finally close out a long-standing related issue on my GitLab projecct. :smile:

**Comment by stevemao** [comment]
@hbetts you can publish now. I have added you :)

**Comment by hbetts** [comment]
Version [1.4.0](https://github.com/stevemao/get-pkg-repo/releases/tag/v1.4.0) has been published.
