### ISSUE TITLE
input argument object is mutated

### ISSUE THREAD

**Issue by revelt** [stevemao/get-pkg-repo#12]
hi all,

It looks like `get-pkg-repo` is mutating the input argument object. Proof is here: https://runkit.com/embed/wvvbqgicfj9v

Basically, I assigned a real package.json into a variable and cloned it into a second-one. Then ran first through `get-pkg-repo` feeding it as argument. That was enough for it not to be `deepEqual` to second-one afterwards.

Either let's **fix this** or **state in the readme** that input args will be **mutated**. This causes issues during unit tests and people should be aware of it.

cheers

**Comment by stevemao** [comment]
The readme states that this depends on normalize-package-data. and if you click on the link you'll know it mutates.

**Comment by hbetts** [comment]
It may help to document that the input is mutated.

Though the usage example, and the wording sort of, demonstrates that the input is mutated by `normalize-package-data`, but it's not obvious that `get-pkg-repo` doesn't deep clone the input and avoid the mutation caused by `normalize-package-data`.

**Comment by revelt** [comment]
@hbetts That's my point. I guess adding extra deps like `lodash.clonedeep` would not be a big issue weight-wise, would it?

Having said that, if you guys feel this issue is a dud and don't agree action should be taken, feel free to close it. I already took measures to safeguard my APIs from it; I just want this documented/sorted for posterity.

**Comment by revelt** [comment]
If I were a maintainer I would have fixed it but documenting this will suffice I guess. Closing.

Having said that, thank you all for maintaining this library. I do appreciate your time and energy spent on this. It's very handy.

**Comment by stevemao** [comment]
I meant that there might be many other hairy details on how they deal with the object. I did it in a generic way, linking them, so that I don't have to duplicate the docs. But I don't mind to add it if requested.
