### ISSUE TITLE
typos.json being an array & Rollup UMD's - can we move it into index.js?

### ISSUE THREAD

**Issue by revelt** [stevemao/get-pkg-repo#14]
hi guys,

I'm consuming this library as a dependency and I'm having trouble when using Rollup to produce the UMD builds — Rollup doesn't like `typos.json` being an **array** data structure (instead of a **plain object**).

<img width="999" alt="issue" src="https://user-images.githubusercontent.com/8344688/33442978-4dfa1c7a-d5ee-11e7-8b87-9fc2ef8f7f10.png">

I ran `typos.json` contents through the JSON validator, it's a valid JSON.

I'm wondering, for the sake of compatibility, would it be worth to migrate that array into the `index.js`?

That separation into a file is done for maintenance purposes but only `index.js` consumes it and also this JSON hasn't been touched since the inception 3 years ago.

Now, before I fork it and re-shuffle my way, I'd be keen to consult with you and maybe get it solved "at the root".

What do you think? Would you consider moving contents of the `typos.json` into `index.js`?

PS. Thank you for creating and maintaining all this.

**Comment by stevemao** [comment]
I'm happy to remove `typos.json`. Yeah this tool was built long time ago and this feature shouldn't be here.

**Comment by hbetts** [comment]
@stevemao I'd be willing to push a commit to move the contents into `index.js`.

However, you're saying that the file isn't needed any longer? Are the alternative spellings either no longer used by the community, or validated by a different tool? (Does `npm` or `yarn` enforce the `repository` field?)

**Comment by stevemao** [comment]
> However, you're saying that the file isn't needed any longer?

I think so

**Comment by revelt** [comment]
Alternatively, we could port JSON's contents into the main JS file and delete the JSON. Problem solved. What do you think?

**Comment by hbetts** [comment]
As a temporary fix, I agree.

To my knowledge, the `repository` field is not strictly enforced by `npm` or `yarn`, so it's quite possible for package publishers to publish packages with a misspelled `repository` field. 

Perhaps we can make the decision later to completely remove typo correction, but we should probably first consider how to notify downstream consumers that we're removing that auto-correction.

**Comment by revelt** [comment]
@hbetts I agree with you. In the meantime, what's really causing trouble is that JSON being external. My apps that consume this lib are breaking because of it, I can't upgrade them. The feature itself is nice to have, I mean it's there and it doesn't hurt. I was seeking to move that array line of code into source JS file..

**Comment by revelt** [comment]
Do you want me to file a PR?

**Comment by hbetts** [comment]
Actually, I am working on it now. I just assigned the issue to myself.

**Comment by revelt** [comment]
Bril.

**Comment by hbetts** [comment]
@revelt if we publish this as a new major version, will that be an issue? (Because we are removing the `typos.json` file, there may be consumers out there that depend directly on it, and it might break their workflows)

**Comment by revelt** [comment]
For me, anything is fine as long as we get rid of JSON. For peeps out there, I think Rollup use outweighs the absence of JSON (which sincerely is not a big thing anyway, just an array). Worst case scenario JSON direct consumers can paste it in the source and mention this lib in the licence. That's fair, isn't it?

**Comment by hbetts** [comment]
@revelt version [2.0.0](https://github.com/stevemao/get-pkg-repo/releases/tag/v2.0.0) has been released.

**Comment by revelt** [comment]
Thank you sir. I updated my deps and I can report my [library](https://github.com/codsen/chlu) now "rolls up" fine – Rollup generates everything without a hitch now.

---

Off topic, very interesting fact, this lib has only 12 [dependents](https://www.npmjs.com/browse/depended/get-pkg-repo) published on npm, but around [25000](https://npmcharts.com/compare/chlu,get-pkg-repo) downloads daily... My lib looks minuscule compared to this, however, looks like very few people actually build **and publish** open source stuff. I think mine is also the first dependent written in ES modules. Whatever those 25000 people-a-day were building, their Rollup would have been failing up until now.
