### ISSUE TITLE
Support GitHub Enterprise Edition

### ISSUE THREAD

**Issue by thiagofelix** [stevemao/get-pkg-repo#3]
One reference implementation:
https://github.com/bahmutov/parse-github-repo-url

**Comment by stevemao** [comment]
> If you find your normalized repository is not correct, It's most likely normalize-package-data or hosted-git-info's problem. Please try to triage the problem before you open an issue here.

I only copied the code from npm/repo. Do you think it's their issue?

**Comment by thiagofelix** [comment]
Sorry for the lack of information.

Well, I am not sure if it is their issue, please help me out.

- [npm/hosted-git-info](https://github.com/npm/hosted-git-info) 
Is supposed to extract fields like [user and project](https://github.com/npm/hosted-git-info/blob/master/index.js#L43), but they don't really [care about ghe](https://github.com/npm/hosted-git-info/blob/master/git-host-info.js)
- [npm/normalize-package-data](https://github.com/npm/normalize-package-data) Only sanitize and clean some values from a package.json. So it won't bother about ghe or not


The issue I see is that a typical ghe installation url looks like that protocol://github.hostname.ext and ``get-pkg-repo`` won't  be able to get the user out of it.

Lastly [conventional-changelog-core](https://github.com/conventional-changelog/conventional-changelog-core/blob/master/lib/get-defaults.js#L140) won't get package owner information either.

This impact the implementation of [conventional-github-releaser/issues/11](https://github.com/conventional-changelog/conventional-github-releaser/issues/11) which is about enabling ghe.

The immediate solution was use [another package as a fallback](https://github.com/conventional-changelog/conventional-github-releaser/pull/13/files#diff-168726dbe96b3ce427e7fedce31bb0bcR100) but really it would be better if we solve it closer to the issue ( here or in npm/hosted-git-info )

Thanks

**Comment by stevemao** [comment]
I think it should be added at npm/hosted-git-info
> npm/hosted-git-info Is supposed to extract fields like user and project, but they don't really care about ghe

Who said that?
https://github.com/npm/hosted-git-info/issues/11

**Comment by thiagofelix** [comment]
No one said, I am judging by the [current implementation](https://github.com/npm/hosted-git-info/blob/master/git-host-info.js)

I didn't see the issue, good to know it is already open.
It's been 5 months already, could we do something here and remove it later when they start supporting it?

**Comment by stevemao** [comment]
`@bahmutov/parse-github-repo-url` looks pretty solid. Maybe we could depend on that.

**Comment by stevemao** [comment]
@thiagofelix Would you be kind enough to send a PR of GHE tests? Thanks a lot.

**Comment by thiagofelix** [comment]
Sure.
