### ISSUE TITLE
Switch back to non-scoped parse-github-repo-url dependency

### ISSUE THREAD

**Issue by mattdsteele** [stevemao/get-pkg-repo#5]
Ref. https://github.com/repo-utils/parse-github-repo-url/pull/1#issuecomment-209533196

Once the non-scoped version of this dependency is available, could you switch `get-pkg-repo` back to using it? We're using a proxied NPM registry that doesn't support scoped modules, and this is a blocker for us to do `npm install`.

**Comment by stevemao** [comment]
PR welcome
