### ISSUE TITLE
test git@foo.local:group/project.git

### ISSUE THREAD

**Issue by stevemao** [stevemao/get-pkg-repo#7]
test git@foo.local:group/project.git

https://github.com/conventional-changelog/standard-version/issues/48#issuecomment-224293522

**Comment by stevemao** [comment]
The url is git@gitlab.foocorp-dev.local:retail/some-project.git

**Comment by kachkaev** [comment]
It feels like `git@...` case is sill not working:

```sh
$ sudo npm i -g get-pkg-repo
$ get-pkg-repo
https://gitlab.foocorp-dev.local/retail/some-project.git
UnknownGitHost {
  domain: 'gitlab.foocorp-dev.local',
  user: 'retail',
  project: 'some-project',
  type: 'gitlab' }
git@gitlab.foocorp-dev.local:retail/some-project.git
UnknownGitHost {
  domain: 'gitlab.foocorp-dev.local',
  user: undefined,
  project: undefined,
  type: 'gitlab' }
```
Facing this here: https://gitlab.com/hyper-expanse/semantic-release-gitlab/issues/10
